{
 "title": "Azure dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Environment", "label": "Environment", "query": "test,preprod,prod" }
  ]
 },
 "panels": [
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http codes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "( http2xx_count_total{resource_group=\"ingress-$Environment\"}/requests_count_total{resource_group=\"ingress-$Environment\"}) * 100",
       "legendFormat": "Success rate"
      }
     ]
    },
    {
     "title": "Requests/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(requests_count_total{resource_group=\"ingress-$Environment\"}[$__range])",
       "legendFormat": "{{resource_name}}"
      }
     ]
    },
    {
     "title": "Avg response time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "httpresponsetime_seconds_average{resource_group=\"ingress-$Environment\"}!=0"
      }
     ]
    },
    {
     "title": "Http codes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "http2xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "2xx"
      },
      {
       "expr": "http3xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "3xx"
      },
      {
       "expr": "http4xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "4xx"
      },
      {
       "expr": "http5xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Data received",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(bytesreceived_bytes_total{resource_group=\"ingress-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Data sent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(bytessent_bytes_total{resource_group=\"ingress-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "requests_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "Requests"
      },
      {
       "expr": "http2xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "2xx"
      },
      {
       "expr": "http3xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "3xx"
      },
      {
       "expr": "http4xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "4xx"
      },
      {
       "expr": "http5xx_count_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Avg cpu time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cputime_seconds_average{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Total IO",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bytesreceived_bytes_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "Received"
      },
      {
       "expr": "- bytessent_bytes_total{resource_group=\"ingress-$Environment\"}",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Egress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg response time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(httpresponsetime_seconds_average{resource_group=\"egress-$Environment\"}) by (resource_name) != 0",
       "legendFormat": "{{resource_name}}"
      }
     ]
    },
    {
     "title": "Data out",
     "type": "graph",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(bytessent_bytes_total{resource_group=\"egress-$Environment\"}) by (resource_name)",
       "legendFormat": "{{resource-name}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "requests_count_total{resource_group=\"egress-$Environment\"} != 0",
       "legendFormat": "{{resource_name}}"
      }
     ]
    },
    {
     "title": "Http codes",
     "type": "table",
     "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(requests_count_total{resource_group=\"egress-$Environment\"}[$__range])"
      },
      {
       "expr": "(sum_over_time(http2xx_count_total{resource_group=\"egress-$Environment\"}[$__range])/\nsum_over_time(requests_count_total{resource_group=\"egress-$Environment\"}[$__range])) * 100"
      },
      {
       "expr": "sum_over_time(http2xx_count_total{resource_group=\"egress-$Environment\"}[$__range])"
      },
      {
       "expr": "sum_over_time(http3xx_count_total{resource_group=\"egress-$Environment\"}[$__range])"
      },
      {
       "expr": "sum_over_time(http4xx_count_total{resource_group=\"egress-$Environment\"}[$__range])"
      },
      {
       "expr": "sum_over_time(http5xx_count_total{resource_group=\"egress-$Environment\"}[$__range])"
      }
     ]
    }
   ]
  },
  {
   "title": "Service bus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total scheduled messages",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "scheduledmessages_count_total{resource_group=\"shared-$Environment\"}",
       "legendFormat": "{{resource_name}}"
      }
     ]
    },
    {
     "title": "Total active messages",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "activemessages_count_total{resource_group=\"shared-$Environment\"} != 0"
      }
     ]
    },
    {
     "title": "Total messages",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "messages_count_total{resource_group=\"shared-$Environment\"} != 0"
      }
     ]
    },
    {
     "title": "Dead lettered/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(deadletteredmessages_count_total{resource_group=\"shared-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Current dead letter",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deadletteredmessages_count_total{resource_group=\"shared-$Environment\"} != 0"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "scheduledmessages_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Scheduled"
      },
      {
       "expr": "incomingmessages_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Incoming"
      },
      {
       "expr": "outgoingmessages_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Outgoing"
      }
     ]
    },
    {
     "title": "Messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "messages_count_average{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Messages count"
      },
      {
       "expr": "activemessages_count_average{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Active"
      },
      {
       "expr": "deadletteredmessages_count_average{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Deadlettered"
      }
     ]
    },
    {
     "title": "Incoming requests/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(incomingrequests_count_total{resource_group=\"shared-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Successful requests/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(successfulrequests_count_total{resource_group=\"shared-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Server errors/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Err/sec" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(servererrors_count_total{resource_group=\"shared-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Total user errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Err/sec" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(usererrors_count_total{resource_group=\"shared-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "incomingrequests_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Incoming"
      },
      {
       "expr": "successfulrequests_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Successful"
      },
      {
       "expr": "servererrors_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "Server errors"
      },
      {
       "expr": "usererrors_count_total{resource_group=\"shared-$Environment\"} != 0",
       "legendFormat": "User errors"
      }
     ]
    }
   ]
  },
  {
   "title": "DatacatalogApi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http codes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "( http2xx_count_total{resource_group=\"datacatalogapi-$Environment\"}/requests_count_total{resource_group=\"datacatalogapi-$Environment\"}) * 100",
       "legendFormat": "Success rate"
      }
     ]
    },
    {
     "title": "Requests/s",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(requests_count_total{resource_group=\"datacatalogapi-$Environment\"}[$__range])",
       "legendFormat": "{{resource_name}}"
      }
     ]
    },
    {
     "title": "Avg response time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "httpresponsetime_seconds_average{resource_group=\"datacatalogapi-$Environment\"}!=0"
      }
     ]
    },
    {
     "title": "Http codes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "http2xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "2xx"
      },
      {
       "expr": "http3xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "3xx"
      },
      {
       "expr": "http4xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "4xx"
      },
      {
       "expr": "http5xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Data received",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(bytesreceived_bytes_total{resource_group=\"datacatalogapi-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "Data sent",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "rate(bytessent_bytes_total{resource_group=\"datacatalogapi-$Environment\"}[$__range])"
      }
     ]
    },
    {
     "title": "requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "requests_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "Requests"
      },
      {
       "expr": "http2xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "2xx"
      },
      {
       "expr": "http3xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "3xx"
      },
      {
       "expr": "http4xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "4xx"
      },
      {
       "expr": "http5xx_count_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "5xx"
      }
     ]
    },
    {
     "title": "Avg cpu time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "cputime_seconds_average{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Total IO",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "bytesreceived_bytes_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "Received"
      },
      {
       "expr": "- bytessent_bytes_total{resource_group=\"datacatalogapi-$Environment\"}",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}