{
 "title": "K8s Cluster Metrics",
 "description": "Dashboard of use from resource of cluster of Kubernetes.\r\nIn this Dashboard it see:\r\n\r\nState of containers from Cluster, State of Pods from Cluster, State of Jobs from Cluster, Deployment and ReplicationController state of Cluster, Nodes number and state of they, Network Activity by namespaces, CPU use in the cluster and CPU use in the cluster by namespaces, Ram memory use in the cluster and Ram memory use in the cluster by namespaces.",
 "tags": [
  "kubernetes",
  "DEFINITIVE"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(node_boot_time{job=\"node-exporter\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "description": "Numbers of containers of cluster in state Running",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "description": "Numbers of containers of cluster in state Terminated",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "description": "Numbers of containers of cluster in state Waiting",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "description": "Numbers of containers of cluster that restarts in the last 30 minutes",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace!=\"kube-system\"}[30m]))"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "description": "Percentage of possible Pods use in the Cluster",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "description": "Graph of Pods use in the cluster",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "description": "Number of Pods in state Running",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "description": "Number of Pods in state Pending",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "description": "Number of Pods in state Failed",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "description": "Number of Pods in state Succeeded",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "description": "Number of Pods in state Unknown",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Jobs Succeeded",
   "type": "singlestat",
   "description": "Number of Succeeded Jobs",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Active",
   "type": "singlestat",
   "description": "Number of Active Jobs",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Jobs Failed",
   "type": "singlestat",
   "description": "Number of Failed Jobs",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Deploy & RC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table-old",
   "description": "List of Deployment with it number of replicas",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "description": "Number replicas of Deployment with state Available",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replication Controller - Up To Date",
   "type": "table-old",
   "description": "List of Replication Controller with it number of replicas",
   "gridPos": { "h": 9, "w": 8, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "kube_replicaset_status_replicas{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Replication Controller Replicas",
   "type": "singlestat",
   "description": "Number replicas of Replication Controller with state Available",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_replicaset_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "description": "Number replicas of Deployment with state Unavailable",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replication Controller - Unavailable",
   "type": "singlestat",
   "description": "Number replicas of Replication Controller with state Unavailable",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{namespace=~\"$namespace\"})\n-\nsum(kube_replicaset_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Total",
   "type": "singlestat",
   "description": "Total number replicas of Deployment",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Replication Controller - Total",
   "type": "singlestat",
   "description": "Total number replicas of Replication Controller",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_replicaset_spec_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "description": "Nodes with Out of Disk",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "description": "Number of Nodes Available",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "description": "Number of Nodes Unavailable",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 31 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)"
    }
   ]
  },
  { "title": "Network Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network Activity by Namespaces",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{}[2m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{}[2m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Cluster CPU Usage Request",
   "type": "singlestat",
   "description": "Percent of use of CPU resource request in the Cluster",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_cpu_cores) by (instance)) / min(sum(kube_node_status_allocatable_cpu_cores) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage Limit",
   "type": "singlestat",
   "description": "Percent of use of CPU resource limit in the Cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 46 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_limits_cpu_cores) by (instance))"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (2m)",
   "type": "singlestat",
   "description": "Cluster CPU usage (2m)",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "SUM(irate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Use of node",
   "type": "graph",
   "description": "CPU Use of node by namespace",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod!=\"\",container!=\"POD\"}[10m]) * 100) by (namespace) / scalar(sum(machine_cpu_cores))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "description": "Cluster CPU capacity in real time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    },
    {
     "expr": "SUM(irate(container_cpu_usage_seconds_total{id=\"/\"}[2m]))",
     "legendFormat": "Currentusage"
    }
   ]
  },
  {
   "title": "Cluster Ram Memory Usage",
   "type": "singlestat",
   "description": "Percent of use of Ram Memory resource request in the Cluster",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 58 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Cluster Ram Memory Usage Limit",
   "type": "singlestat",
   "description": "Percent of use of Ram Memory resource limit in the Cluster",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 58 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance)) / min(sum(kube_node_status_allocatable_memory_bytes) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Use Ram memory Cluster",
   "type": "singlestat",
   "description": "Use Ram memory Cluster",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 58 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",container_name!=\"POD\"})"
    }
   ]
  },
  {
   "title": "Ram memory Use of node",
   "type": "graph",
   "description": "Ram memory Use of node by namespace",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"}) by (namespace,container_name)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Cluster Ram memory Capacity",
   "type": "graph",
   "description": "Cluster Ram memory capacity in real time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(min(sum(kube_node_status_allocatable_memory_bytes) by (instance)))",
     "legendFormat": "Allocatable Memory"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_requests_memory_bytes) by (instance))",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "max(sum(kube_pod_container_resource_limits_memory_bytes) by (instance))",
     "legendFormat": "Limits Memory"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",container_name!=\"POD\"})",
     "legendFormat": "Currentusage"
    }
   ]
  }
 ]
}