{
 "title": "Azure dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Service bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scheduled messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scheduledmessages_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Active messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(activemessages_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Total messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(messages_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Dead letter messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(deadletteredmessages_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Incoming requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(incomingrequests_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(successfulrequests_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Server errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(servererrors_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "User errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(usererrors_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(messages_count_total) by (resource_name)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(scheduledmessages_count_total) by (resource_name)",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(incomingmessages_count_total) by (resource_name)",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(activemessages_count_total) by (resource_name)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(outgoingmessages_count_total) by (resource_name)",
     "legendFormat": "Outgoing"
    },
    {
     "expr": "sum(deadletteredmessages_count_total) by (resource_name)",
     "legendFormat": "Deadlettered"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(incomingrequests_count_total) by (resource_name)",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(successfulrequests_count_total) by (resource_name)",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(servererrors_count_total) by (resource_name)",
     "legendFormat": "Server errors"
    },
    {
     "expr": "sum(usererrors_count_total) by (resource_name)",
     "legendFormat": "User errors"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(activeconnections_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Opened connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(connectionsopened_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Closed connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(connectionsclosed_count_total) by (resource_name)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(activeconnections_count_total) by (resource_name)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(connectionsopened_count_total) by (resource_name)",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(connectionsclosed_count_total) by (resource_name)",
     "legendFormat": "Closed"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Ingress Bytes In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bytesreceived_bytes_average{resource_group=~\"ingress-.*\"}[2m])) by (resource_name)",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Egress Bytes Out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bytessent_bytes_average{resource_group=~\"egress-.*\"}[2m])) by (resource_name)",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  {
   "title": "Core I/O",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bytesreceived_bytes_average{resource_group=~\"core-.*\"}[2m])) by (resource_name)",
     "legendFormat": "{{resource_name}}"
    },
    {
     "expr": "- sum(rate(bytessent_bytes_average{resource_group=~\"core-.*\"}[2m])) by (resource_name)",
     "legendFormat": "{{resource_name}}"
    }
   ]
  },
  { "title": "Functions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Function execution count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "Executions" }
   ],
   "targets": [
    {
     "expr": "sum(functionexecutioncount_count_total{resource_group=~\"core-.*\"}) by (resource_name)",
     "legendFormat": "{{resouce_name}}"
    }
   ]
  }
 ]
}